export const MEDICAL_TERMS = [
  "ache",
  "abdominal pain",
  "acid reflux",
  "back pain",
  "bleeding",
  "blurred vision",
  "body pain",
  "breathing difficulty",
  "chest pain",
  "chills",
  "constipation",
  "diarrhea",
  "dizziness",
  "earache",
  "fatigue",
  "headache",
  "hearing loss",
  "joint pain",
  "loss of appetite",
  "loss of consciousness",
  "loss of smell",
  "loss of taste",
  "nausea",
  "neck pain",
  "night sweats",
  "numbness",
  "palpitations",
  "shortness of breath",
  "sore throat",
  "swelling",
  "vomiting",
  "allergy",
  "anxiety",
  "dehydration",
  "malnutrition",
  "pain",
  "symptom",
  "wellness",

  "appendicitis",
  "arthritis",
  "asthma",
  "autism",
  "alzheimer's",
  "alzheimer disease",
  "anemia",
  "angina",
  "ankylosing spondylitis",
  "arrhythmia",
  "bipolar disorder",
  "bacteria",
  "blood pressure",
  "blood sugar",
  "bone",
  "breast",
  "cancer",
  "cataract",
  "cardiac",
  "cardiology",
  "celiac disease",
  "cerebral palsy",
  "chickenpox",
  "cholera",
  "chronic fatigue syndrome",
  "cirrhosis",
  "crohn disease",
  "crohn's disease",
  "clinic",
  "cold",
  "condition",
  "cough",
  "covid",
  "covid 19",
  "dementia",
  "dentist",
  "dengue",
  "depression",
  "diabetes",
  "dialysis",
  "disease",
  "doctor",
  "down syndrome",
  "eczema",
  "endometriosis",
  "emergency",
  "endocrine",
  "ent",
  "epilepsy",
  "fever",
  "flu",
  "fungal",
  "gastro",
  "gastroenterology",
  "gallstones",
  "glaucoma",
  "gout",
  "hepatitis",
  "hernia",
  "herpes",
  "gynecology",
  "health",
  "healthcare",
  "heart",
  "hospital",
  "hiv",
  "hypertension",
  "hypotension",
  "hypothyroidism",
  "hyperthyroidism",
  "infection",
  "injury",
  "insomnia",
  "intensive care",
  "ivf",
  "jaundice",
  "kidney",
  "leukemia",
  "liver",
  "lupus",
  "malaria",
  "medicine",
  "meningitis",
  "migraine",
  "mri",
  "multiple sclerosis",
  "muscular dystrophy",
  "myocardial infarction",
  "neurology",
  "neuralgia",
  "obesity",
  "obstetrics",
  "oncology",
  "orthopedic",
  "orthopaedic",
  "osteoporosis",
  "parkinson's disease",
  "parkinson disease",
  "patient",
  "pharmacy",
  "piles",
  "physiotherapy",
  "physician",
  "pregnancy",
  "prescription",
  "prostate",
  "psychiatry",
  "psychologist",
  "psoriasis",
  "radiology",
  "rash",
  "rectal",
  "rehab",
  "respiratory",
  "report",
  "retina",
  "rheumatology",
  "rheumatoid arthritis",
  "scoliosis",
  "seizure",
  "sexually transmitted",
  "sleep apnea",
  "spine",
  "stomach",
  "stroke",
  "surgery",
  "thyroid",
  "therapy",
  "treatment",
  "tumor",
  "ultrasound",
  "uti",
  "vaccine",
  "virus",
  "wound",

  "bird flu",
  "botulism",
  "brucellosis",
  "common cold",
  "food poisoning",
  "gastroenteritis",
  "hookworm",
  "influenza",
  "measles",
  "mumps",
  "norovirus",
  "pneumonia",
  "rabies",
  "ringworm",
  "rotavirus",
  "salmonella",
  "sepsis",
  "shigella",
  "strep throat",
  "tetanus",
  "toxoplasmosis",
  "tuberculosis",
  "typhoid",
  "whooping cough",
  "yellow fever",

  "accident",
  "animal bite",
  "assault injury",
  "avalanche injury",
  "bicycle accident",
  "black eye",
  "blunt force trauma",
  "bone fracture",
  "brain injury",
  "burn",
  "car accident",
  "chemical burn",
  "concussion",
  "crush injury",
  "cut",
  "dislocation",
  "drowning",
  "electric shock",
  "fall injury",
  "fire injury",
  "frostbite",
  "head injury",
  "heat exhaustion",
  "heat stroke",
  "industrial accident",
  "internal bleeding",
  "ligament tear",
  "motorcycle accident",
  "neck injury",
  "poisoning",
  "road accident",
  "scald",
  "shock",
  "spinal cord injury",
  "sprain",
  "stab wound",
  "sports injury",
  "strain",
  "trauma",
  "traumatic brain injury",
  "water accident",
  "workplace accident",
];

export const MEDICAL_ABBREVIATIONS = new Set([
  "a&e",
  "aids",
  "bp",
  "cbc",
  "cpr",
  "ct",
  "ecg",
  "eeg",
  "emr",
  "er",
  "hiv",
  "icu",
  "lab",
  "mri",
  "ncd",
  "obgyn",
  "pcos",
  "pcr",
  "pt",
  "tb",
  "tsh",
  "uti",
  "vitals",
  "xray",
]);

const MEDICAL_SUFFIX_PATTERN =
  /\b[a-z]+(?:algia|emia|iasis|itis|megaly|oma|opathy|penia|phobia|plasia|sclerosis|syndrome|trophy|virus)\b/;

const NON_LATIN_MEDICAL_TERMS = [
  "बुखार",
  "दर्द",
  "अस्पताल",
  "डॉक्टर",
  "दवा",
  "इलाज",
  "स्वास्थ्य",
  "बीमारी",
  "लक्षण",
  "रिपोर्ट",
  "दिल",
  "गुर्दा",
  "कैंसर",
  "मधुमेह",
  "गर्भावस्था",
  "ਪੰਜਾਬੀ",
  "ਬੁਖਾਰ",
  "ਦਰਦ",
  "ਹਸਪਤਾਲ",
  "ਡਾਕਟਰ",
  "ਦਵਾਈ",
  "ਇਲਾਜ",
  "ਸਿਹਤ",
  "ਬਿਮਾਰੀ",
  "ਲੱਛਣ",
  "ਰਿਪੋਰਟ",
  "ਦਿਲ",
  "ਗੁਰਦਾ",
  "ਕੈਂਸਰ",
  "ਸ਼ੂਗਰ",
];

export function isMedicalQuery(value = "") {
  const rawQuery = String(value).toLowerCase().trim();
  const normalizedQuery = rawQuery
    .replace(/[^a-z0-9\s:-]/g, " ")
    .replace(/\s+/g, " ")
    .trim();

  if (!normalizedQuery) {
    return NON_LATIN_MEDICAL_TERMS.some((term) => rawQuery.includes(term));
  }

  const queryWords = normalizedQuery.split(" ");
  const containsMedicalTerm = MEDICAL_TERMS.some((term) => {
    if (term.includes(" ")) {
      return (
        normalizedQuery === term ||
        normalizedQuery.includes(` ${term} `) ||
        normalizedQuery.startsWith(`${term} `) ||
        normalizedQuery.endsWith(` ${term}`)
      );
    }

    return queryWords.includes(term);
  });

  return (
    containsMedicalTerm ||
    queryWords.some((word) => MEDICAL_ABBREVIATIONS.has(word)) ||
    NON_LATIN_MEDICAL_TERMS.some((term) => rawQuery.includes(term)) ||
    MEDICAL_SUFFIX_PATTERN.test(normalizedQuery)
  );
}
